# Generated by Django 3.1.5 on 2021-01-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210129_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved')], default=0),
        ),
    ]
